---
- name: Setup My Manjaro Dev Machine
  hosts: [localhost, all]
  roles:
    - kewlfft.aur
  tasks:
    - name: Upgrade
      become: yes
      become_method: sudo
      pacman:
        upgrade: yes
  
    ### Basic Tools (Arch) ###
    - name:
      become: yes
      become_method: sudo
      pacman:
        name: fakeroot
    - name:
      become: yes
      become_method: sudo
      pacman:
        name: gcc
    - name:
      become: yes
      become_method: sudo
      pacman:
        name: wget
    - name:
      become: yes
      become_method: sudo
      pacman:
        name: git

    ### Shell Setup ###
    - name: ZSH
      become: yes
      become_method: sudo
      pacman:
        update_cache: yes
        name: zsh
    - name: Change Shell To ZSH 
      become: yes
      become_method: sudo
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
    - name: Oh-My-Zsh
      shell:
        warn: no
        cmd: wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
        creates: /home/{{ ansible_user_id}}/.oh-my-zsh
    - name: FZF
      become: yes
      become_method: sudo
      pacman:
        name: fzf
    - name: Autojump
      aur:
        name: autojump
    - name: Oh-My-Zsh Plugins
      replace:
        path: /home/{{ ansible_user_id }}/.zshrc
        regexp: '^plugins=\(git\)$'
        replace: "plugins=(git fzf autojump)"

    ### Node & WebDev Tools ###
    - name: NVM
      shell:
        warn: no
        cmd: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | zsh
        creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh
    - name: Visual Studio Code
      aur:
        name: visual-studio-code-bin
    - name: Ferdi
      aur:
        name: ferdi
    - name: Microsoft Teams
      aur:
        name: teams
    - name: Vivaldi
      aur:
        name: vivaldi

    ### Docker ###
    - name: Docker
      become: yes
      become_method: sudo
      pacman:
        name: docker
    - name: Compose
      become: yes
      become_method: sudo
      pacman:
        name: docker-compose

    ### Vagrant ###
    - name: Vagrant
      become: yes
      become_method: sudo
      pacman:
        name: vagrant

    ### General Tools ###
    - name: Autokey
      aur:
        name: autokey
    - name: Virt-Manager
      become: yes
      become_method: sudo
      pacman:
        name: virt-manager
    - name: bat
      become: yes
      become_method: sudo
      pacman:
        name: bat
    - name: Guake
      become: yes
      become_method: sudo
      pacman:
        name: guake

    ### User Groups ###
    - name: User Groups
      user:
        name: "{{ ansible_user_id }}"
        groups: [libvirt, docker, uucp, kvm]
        append: yes
    - name: Reload Groups
      meta: reset_connection
