---
- name: Setup My Manjaro Dev Machine
  hosts: localhost
  roles:
  - kewlfft.aur
  tasks:
    - name: Install ZSH
      pacman:
        name: zsh
    - name: Install Oh-My-Zsh
      shell:
        warn: no
        cmd: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: /home/{{ ansible_user_id}}/.oh-my-zsh
    - name: Install FZF
      pacman:
        name: fzf
    - name: Install Autojump
      pacman:
        name: autojump
    - name: Install Visual Studio Code
      aur:
        name: visual-studio-code-bin
    - name: Install Ferdi
      aur:
        name: ferdi
    - name: Install Microsoft Teams
      aur:
        name: teams
    - name: Install NVM
      shell:
        warn: no
        cmd: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | zsh
        creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh

