---
- name: Setup My Manjaro Dev Machine
  hosts: [localhost, all]
  tasks:
    - name: Upgrade
      become: true
      become_method: sudo
      pacman:
        upgrade: true

    ### Basic Tools (Arch) ###
    - name: Essential Tools(fakeroot)
      become: true
      become_method: sudo
      pacman:
        name: fakeroot
    - name: Essential Tools(gcc)
      become: true
      become_method: sudo
      pacman:
        name: gcc
    - name: Essential Tools(wget)
      become: true
      become_method: sudo
      pacman:
        name: wget
    - name: Essential Tools(git)
      become: true
      become_method: sudo
      pacman:
        name: git

    ### Shell Setup ###

    ### Node & WebDev Tools ###
    - name: NVM
      shell: |
         wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
         echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
         echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.zshrc
         echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >> ~/.zshrc

      args:
        creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh
    - name: Visual Studio Code
      kewlfft.aur.aur:
        name: visual-studio-code-bin

    ### Docker ###
    - name: Docker
      become: true
      become_method: sudo
      pacman:
        name: docker
    - name: Compose
      become: true
      become_method: sudo
      pacman:
        name: docker-compose

    ### Vagrant ###
    - name: Vagrant
      become: true
      become_method: sudo
      pacman:
        name: vagrant

    ### General Tools ###
    - name: Espanso
      kewlfft.aur.aur:
        name: espanso-bin
    - name: Virt-Manager
      become: true
      become_method: sudo
      pacman:
        name: virt-manager
    - name: bat
      become: true
      become_method: sudo
      pacman:
        name: bat
    - name: Yakuake
      become: true
      become_method: sudo
      pacman:
        name: yakuake

    ### Communication ###
    - name: Ferdium
      kewlfft.aur.aur:
        name: ferdium-bin

    ### User Groups ###
    - name: User Groups
      become: true
      user:
        name: "{{ ansible_user_id }}"
        groups: [libvirt, docker, uucp, kvm]
        append: true
    - name: Reload Groups
      meta: reset_connection
